python3 assertion_error.py