python3 type_error_2.py