python3 value_error.py